colorscheme wombat
if has("mac")
  set guifont=Menlo:h14.00
  set fuopt=maxhorz,maxvert
else
  set gfn=Monospace\ 13
end

set guioptions-=T  "remove toolbar
set guioptions-=m  "remove menu

set lines=47
set columns=161
