#!/bin/bash

ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

brew install ack
brew install postgresql
brew install redis
brew install tig
brew install apple-gcc42
brew install bash-completion
brew install gdbm
brew install libxml2
brew install mysql
brew install qt
brew install ruby
brew install tmux
brew install curl
brew install git
brew install openssl
brew install wget
